name: Update EPG

on:
  schedule:
    - cron: '10 */6 * * *'  # Executa a cada 6 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  update_epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update script
      run: python 8p4ey8mvw5fq89z8ng1v.py

    - name: Save logs
      run: dmesg > logs.txt
