name: Update EPG

on:
  schedule:
    - cron: '10 23 * * *'  # Executa diariamente às 23h
#    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
#    - cron: '0 */2 * * *'  # Executa a cada duas horas
  workflow_dispatch:  # Permite execução manual

jobs:
  update_epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update script

      run: python ScriptEPG.XML.py

#      run: python update_epg.py
####################
